name: ros2-car-ci

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container: ros:jazzy-ros-base
    steps:
      - uses: actions/checkout@v4
      - name: Install build and test dependencies
        run: |
          apt-get update
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y
          apt-get install -y python3-colcon-common-extensions
      - name: Build
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --event-handlers console_direct+
      - name: Test
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          source install/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
